version: '2'
services:
  web:
    build: .
    volumes:
      - ../sites/framework:/var/www/shared
  nginx-dupeczki:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes_from:
      - web
    ports:
      - "8001:8001"
    links:
      - fpm
    volumes:
      - ../sites/dupeczki:/var/www/html
  nginx-ministranci:
      build:
        context: .
        dockerfile: ./nginx/Dockerfile
      volumes_from:
        - web
      ports:
        - "8002:8002"
      links:
        - fpm
      volumes:
        - ../sites/ministranci:/var/www/html
  nginx-woodstock:
      build:
        context: .
        dockerfile: ./nginx/Dockerfile
      volumes_from:
        - web
      ports:
        - "8003:8003"
      links:
        - fpm
      volumes:
        - ../sites/woodstock:/var/www/html
  haproxy:
    build:
      context: .
      dockerfile: ./haproxy/Dockerfile
    ports:
      - "80:80"
    links:
      - nginx-woodstock
      - nginx-dupeczki
      - nginx-ministranci
  fpm:
    build:
      context: .
      dockerfile: ./fpm/Dockerfile
    volumes_from:
      - web
