version: '2'
services:
  nginx-dupeczki:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    expose:
      - 80
    links:
      - fpm
    volumes:
      - ../sites/dupeczki:/var/www/dupeczki
      - ../sites/framework:/var/www/shared
  nginx-ministranci:
      build:
        context: .
        dockerfile: ./nginx/Dockerfile
      expose:
        - 80
      links:
        - fpm
      volumes:
        - ../sites/ministranci:/var/www/ministranci
        - ../sites/framework:/var/www/shared
  nginx-woodstock:
      build:
        context: .
        dockerfile: ./nginx/Dockerfile
      expose:
        - 80
      links:
        - fpm
      volumes:
        - ../sites/woodstock:/var/www/woodstock
        - ../sites/framework:/var/www/shared
  haproxy:
    build:
      context: .
      dockerfile: ./haproxy/Dockerfile
    ports:
      - "80:80"
    links:
      - nginx-woodstock
      - nginx-dupeczki
      - nginx-ministranci
  fpm:
    build:
      context: .
      dockerfile: ./fpm/Dockerfile
    volumes:
      - ../sites/woodstock:/var/www/woodstock
      - ../sites/dupeczki:/var/www/dupeczki
      - ../sites/ministranci:/var/www/ministranci
  fpm-dupeczki:
      build:
        context: .
        dockerfile: ./fpm/Dockerfile.fpm56
      volumes:
        - ../sites/woodstock:/var/www/woodstock
        - ../sites/dupeczki:/var/www/dupeczki
        - ../sites/ministranci:/var/www/ministranci

