version: '2'
services:
  web:
    build: .
    volumes:
      - ../sites/framework:/var/www/shared
  nginx-dupeczki:
    build:.
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes_from:
      - web
    ports:
      - "80:8001"
    links:
      - fpm
    volumes:
      - ../sites/dupeczki:/var/www/html
  nginx-ministranci:
      build:.
        context: .
        dockerfile: ./nginx/Dockerfile
      volumes_from:
        - web
      ports:
        - "80:8002"
      links:
        - fpm
      volumes:
        - ../sites/ministranci:/var/www/html
  nginx-woodstock:
      build:.
        context: .
        dockerfile: ./nginx/Dockerfile
      volumes_from:
        - web
      ports:
        - "80:8003"
      links:
        - fpm
      volumes:
        - ../sites/woodstock:/var/www/html
  fpm:
    image: php:fpm
    volumes_from:
      - web
    volumes:
      - ../sites:/var/www
